### ISSUE TITLE
Error- couldn't find any output plugin named riemann

### ISSUE THREAD

**Issue by Rajeshkumar123** [logstash-plugins/logstash-output-riemann#10]
I have installed logstash-output-riemann plugin normally in my logstash. I followed the same installation process which I did to install other plugins(gem). I have checked the gem folder of my logstash , I can see the logstash-output-riemann folder with corresponding files. I am facing this issue in my Linux box, it was working fine in windows machine.

My config will looks like below:
input {
   courier {
        port => 10544 
        transport=>"tcp"

```
}
```

}

filter{
...
...
}
output{
if [type] == "error" {
    riemann{
        host=>localhost
        riemann_event =>  {
                        "service"=> "system_log"  
                        "description"=> "%{name.systemName}"
                        "metric" => "%{metric}"
                        "ttl" => "%{ttl}"  
                      }  
    }
  }

I am getting below error,

 Couldn't find any output plugin named 'riemann'. Are you sure this is correct? Trying to load the riemann output plugin resulted in this error: no such file to load -- logstash/outputs/riemann

**Comment by jhitze** [comment]
Are you sure you did this correctly? I just did it and it worked fine.

```
/opt/logstash$ sudo bin/plugin install logstash-output-riemann
Validating logstash-output-riemann
Installing logstash-output-riemann
Installation successful
```

**Comment by Rajeshkumar123** [comment]
I have installed the latest version in logstash 1.5.4 and the issue was resolved.
