### ISSUE TITLE
[request] release and publish 3.0.0

### ISSUE THREAD

**Issue by boernd** [logstash-plugins/logstash-output-riemann#18]
Would be great if the plugin could be released so it would work with 5.x out of the box. Or is there a blocker?

riemann-client dependency update to 0.2.6 would also be appreciated.

**Comment by jordansissel** [comment]
@boernd is there something preventing it from working? (Asking because I don't use it and dont' usually work on this plugin)

**Comment by boernd** [comment]
@jordansissel I have build the master locally and it is running for several days in my environment without any issues (LS 5.0.0, riemann 0.2.10). It seems everything has been prepared in #17 (except riemann-client dep update), just the release is missing.

**Comment by jordansissel** [comment]
@boernd Thank you for these details <3

I am running the publish job now; hopefully shortly it will be available.

**Comment by jordansissel** [comment]
Version 3.0.0 is published.

https://rubygems.org/gems/logstash-output-riemann/versions/3.0.0

**Comment by boernd** [comment]
Thx!
