### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by hmrm** [logstash-plugins/logstash-output-riemann#2]
NoMethodError: undefined method `each' for #LogStash::Event:0x6255eda6
     map_fields at /home/hmaxwell/conversion-hekad-config/logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-riemann-0.1.1/lib/logstash/outputs/riemann.rb:111
        receive at /home/hmaxwell/conversion-hekad-config/logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-riemann-0.1.1/lib/logstash/outputs/riemann.rb:145
         handle at /home/hmaxwell/conversion-hekad-config/logstash/logstash/lib/logstash/outputs/base.rb:86
     initialize at (eval):28
           call at org/jruby/RubyProc.java:271
         output at /home/hmaxwell/conversion-hekad-config/logstash/logstash/lib/logstash/pipeline.rb:272
   outputworker at /home/hmaxwell/conversion-hekad-config/logstash/logstash/lib/logstash/pipeline.rb:231
  start_outputs at /home/hmaxwell/conversion-hekad-config/logstash/logstash/lib/logstash/pipeline.rb:160

**Comment by hmrm** [comment]
I think #1 fixes this

**Comment by corradio** [comment]
Same issue here.

**Comment by falzm** [comment]
Same issue with Logstash 1.5.0.

**Comment by suyograo** [comment]
#5 fixes this
