### ISSUE TITLE
Exceptions should log to error

### ISSUE THREAD

**Issue by jhitze** [logstash-plugins/logstash-output-riemann#8]
https://github.com/logstash-plugins/logstash-output-riemann/blob/master/lib/logstash/outputs/riemann.rb#L163

It's logging to debug, which is not helpful if there are exceptions.

**Comment by guyboertje** [comment]
Agreed.  I will fix this.

**Comment by jhitze** [comment]
Why was this closed?

**Comment by nukemberg** [comment]
it was fixed by commit 04bea14
